- name: spark setup
  hosts: all
  remote_user: ubuntu
  roles:  
    - {
        role: andrewrothstein.hadoop,
        hadoop_version : '{{hadoop_version}}',
        hadoop_checksums: {
            '2.7.4': 'sha256:8f791bfcfa5bb7c7ccd09910d490c02910dda93b19936ec2aedb8930bc5be111',
            '2.7.6': 'sha256:f2327ea93f4bc5a5d7150dee8e0ede196d3a77ff8526a7dd05a48a09aae25669',
            '2.8.2': 'sha256:aea99c7ce8441749d81202bdea431f1024f17ee6e0efb3144226883207cc6292',
            '2.9.0': 'sha256:8d48666f29f9ade6ed2762b7a9edab177bad2c57396f43d0ffd6a269d54f6fe1',
            '3.0.0': 'sha256:726e28fa7aea71e4587ce91ed3d96c56b15777fc859c09a7438a6d0092e08c74',
            '3.0.1': 'sha256:da79ba1ac659538982604c3da94da50621399f85fb74da4a9037feae1dbd920c',
            '3.1.0': 'sha256:670d2ced595fa42d9fa1a93c4e39b39f47002cad1553d9df163ee828ca5143e7',
        },
        hadoop_parent_dir: '{{ install_parent_dir }}'

    }
    - {
        role: andrewrothstein.spark,
        spark_ver: '{{spark_version}}',
        spark_parent_dir: '{{ install_parent_dir }}'
      }

- name: set hadoop slaves
  template:
    src: templates/slaves.j2
    dest: '{{ hadoop_conf_dir }}'

- name: set spark slaves
  template:
    src: templates/slaves.j2
    dest: '{{ slaves_conf_dir }}'